name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get version using custom Gradle task
      id: gradle_version
      run: |
        VERSION=$(./gradlew printVersion -q)
        
        if [ -z "$VERSION" ]; then
          echo "Error: Could not get version from Gradle"
          exit 1
        fi
        
        echo "Project version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Build the Docker image
      run: |
        echo "Building Docker image with version: ${{ steps.gradle_version.outputs.VERSION }}"
        docker build . --file Dockerfile --tag binarysimple/simple-auth-service:${{ steps.gradle_version.outputs.VERSION }}
