name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: false

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Get version from Gradle task
      id: gradle_version
      run: |
          # printVersion
          # Получаем версию проекта из Gradle, игнорируя все сообщения о загрузке
          VERSION=$(./gradlew printVersion -q --no-scan --console=plain 2>&1 | tail -n 1 | tr -d '[:space:]')
          
          if [ -z "$VERSION" ]; then
            echo "Error: Could not get version from Gradle"
            exit 1
          fi
          
          # Убедимся, что версия соответствует ожидаемому формату (например, 0.0.2)
          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            # Если версия не в формате x.x.x, попробуем извлечь ее
            VERSION=$(echo "$VERSION" | grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+" | head -n 1)
          fi
          
          echo "✅ Project version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
#    - name: Get version using custom Gradle task
#      id: gradle_version
#      run: |
#        VERSION=$(./gradlew printVersion -q)
#
#        if [ -z "$VERSION" ]; then
#          echo "Error: Could not get version from Gradle"
#          exit 1
#        fi
#
#        echo "Project version: $VERSION"
#        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Build the Docker image
      run: |
        echo "Building Docker image with version: ${{ steps.gradle_version.outputs.VERSION }}"
        docker build . --file Dockerfile --tag binarysimple/simple-auth-service:${{ steps.gradle_version.outputs.VERSION }}
